def Printing(x,i,f):
    f.write(str(i))
    f.write(')')
    f.write(' ')
    f.write(x.nome)
    f.write(':')
    f.write(str(x.punteggio))
    f.write(' (')
    f.write(str(x.tornei))
    f.write(' tornei)')